DAGK_1461744/DAGK_1461744/Areas/Admin/Controllers/LoaiSanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAGK_1461744.Models.BUS;
using DAGKConnection;

namespace DAGK_1461744.Areas.Admin.Controllers
{
    public class LoaiSanPhamController : Controller
    {
        // GET: Admin/LoaiSanPham
        public ActionResult Index(int page = 1)
        {
            var dsSanPham = SPAdminBUS.DanhSachLoaiSPAdmin(page, 10);
            return View(dsSanPham);
        }

        // GET: Admin/LoaiSanPham/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/LoaiSanPham/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/LoaiSanPham/Create
        [HttpPost]
        public ActionResult Create(LoaiSanPham a)
        {
            try
            {
                // TODO: Add insert logic here
                SPAdminBUS.ThemLoaiSP(a);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/LoaiSanPham/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Admin/LoaiSanPham/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/LoaiSanPham/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/LoaiSanPham/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

DAGK_1461744/DAGK_1461744/Areas/Admin/Controllers/SanPhamAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAGK_1461744.Models.BUS;
using DAGKConnection;

namespace DAGK_1461744.Areas.Admin.Controllers
{
    public class SanPhamAdminController : Controller
    {
        

        public ActionResult Index(int page = 1)
        {
            var dsSanPham = SPAdminBUS.DanhSachADmin(page, 20);
            return View(dsSanPham);
        }


        // GET: Admin/SanPhamAdmin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/SanPhamAdmin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/SanPhamAdmin/Create
        [HttpPost,ValidateInput(false)]
        public ActionResult Create(SanPham a)
        {
            try
            {
                {
                    // TODO: Add insert logic here
                    //Hàm thêm
                    if (HttpContext.Request.Files.Count > 0) { }

                    var hpf = HttpContext.Request.Files[0];
                    if (hpf.ContentLength > 0)
                    {
                        string fileName = Guid.NewGuid().ToString();
                        string fileName1 = Guid.NewGuid().ToString();
                        string fileName2 = Guid.NewGuid().ToString();
                        string fileName3 = Guid.NewGuid().ToString();


                        string fullPathWithFileName = "/img/" + fileName +".jpg" ;
                        string fullPathWithFileName1 = "/img/" + fileName1 + ".jpg";
                        string fullPathWithFileName2 = "/img/" + fileName2 + ".jpg";
                        string fullPathWithFileName3 = "/img/" + fileName3 + ".jpg";

                        hpf.SaveAs(Server.MapPath(fullPathWithFileName));
                        hpf.SaveAs(Server.MapPath(fullPathWithFileName1));
                        hpf.SaveAs(Server.MapPath(fullPathWithFileName2));
                        hpf.SaveAs(Server.MapPath(fullPathWithFileName3));
                        a.HinhAnh = fullPathWithFileName;
                        a.HinhAnh1 = fullPathWithFileName1;
                        a.HinhAnh2 = fullPathWithFileName2;
                        a.HinhAnh3 = fullPathWithFileName3;

                    }
                }
                // TODO: Add insert logic here
                SPAdminBUS.ThemSP(a);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/SanPhamAdmin/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Admin/SanPhamAdmin/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/SanPhamAdmin/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/SanPhamAdmin/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

DAGK_1461744/DAGK_1461744/Areas/Admin/Views/Shared/_Mainlayout.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <title>Admin</title>

    <meta name="robots" content="noindex, nofollow" />

    <link rel="shortcut icon" href="images/icon.png" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="~/Asset/crown/css/main.css" />
    <link rel="stylesheet" type="text/css" href="~/Asset/css/css.css" media="screen" />

    <link rel="stylesheet" href="~/css/owl.carousel.css" />
    <link rel="stylesheet" href="~/style.css" />
    <link rel="stylesheet" href="~/css/responsive.css" />
    <script type="text/javascript">
        var admin_url = '';
        var base_url = '';
        var public_url = '';
    </script>

    <script type="text/javascript" src="~/Asset/js/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="~/Asset/js/jquery/jquery-ui.min.js"></script>

    <script type="text/javascript" src="~/Asset/js/plugins/spinner/jquery.mousewheel.js"></script>

    <script type="text/javascript" src="~/Asset/js/plugins/forms/uniform.js"></script>
    <script type="text/javascript" src="~/Asset/js/plugins/forms/jquery.tagsinput.min.js"></script>
    <script type="text/javascript" src="~/Asset/js/plugins/forms/autogrowtextarea.js"></script>
    <script type="text/javascript" src="~/Asset/js/plugins/forms/jquery.maskedinput.min.js"></script>
    <script type="text/javascript" src="~/Asset/js/plugins/forms/jquery.inputlimiter.min.js"></script>

    <script type="text/javascript" src="~/Asset/js/plugins/tables/datatable.js"></script>
    <script type="text/javascript" src="~/Asset/js/plugins/tables/tablesort.min.js"></script>
    <script type="text/javascript" src="~/Asset/js/plugins/tables/resizable.min.js"></script>

    <script type="text/javascript" src="~/Asset/js/plugins/ui/jquery.tipsy.js"></script>
    <script type="text/javascript" src="~/Asset/js/plugins/ui/jquery.collapsible.min.js"></script>
    <script type="text/javascript" src="~/Asset/js/plugins/ui/jquery.progress.js"></script>
    <script type="text/javascript" src="~/Asset/js/plugins/ui/jquery.timeentry.min.js"></script>
    <script type="text/javascript" src="~/Asset/js/plugins/ui/jquery.colorpicker.js"></script>
    <script type="text/javascript" src="~/Asset/js/plugins/ui/jquery.jgrowl.js"></script>
    <script type="text/javascript" src="~/Asset/js/plugins/ui/jquery.breadcrumbs.js"></script>
    <script type="text/javascript" src="~/Asset/js/plugins/ui/jquery.sourcerer.js"></script>

    <script type="text/javascript" src="~/Asset/js/custom.js"></script>


    <script type="text/javascript" src="~/Asset/js/ckeditor/ckeditor.js"></script>
    <script type="text/javascript" src="~/Asset/js/jquery/chosen/chosen.jquery.min.js"></script>
    <script type="text/javascript" src="~/Asset/js/jquery/scrollTo/jquery.scrollTo.js"></script>
    <script type="text/javascript" src="~/Asset/js/jquery/number/jquery.number.min.js"></script>
    <script type="text/javascript" src="~/Asset/js/jquery/formatCurrency/jquery.formatCurrency-1.4.0.min.js"></script>
    <script type="text/javascript" src="~/Asset/js/jquery/zclip/jquery.zclip.js"></script>

    <script type="text/javascript" src="~/Asset/js/jquery/colorbox/jquery.colorbox.js"></script>
    <link rel="stylesheet" type="text/css" href="~/Asset/crown/js/jquery/colorbox/colorbox.css" media="screen" />
    <script type="text/javascript" src="~/Scripts/tinymce/tinymce.js"></script>
    <script>
        tinymce.init({
            selector: '.tinymce',
            height: 500,
            theme: 'modern',
            plugins: [
              'advlist autolink lists link image charmap print preview hr anchor pagebreak',
              'searchreplace wordcount visualblocks visualchars code fullscreen',
              'insertdatetime media nonbreaking save table contextmenu directionality',
              'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc'
            ],
            toolbar1: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
            toolbar2: 'print preview media | forecolor backcolor emoticons | codesample',
            image_advtab: true,
        });
    </script>
    <script type="text/javascript" src="~/Asset/js/custom_admin.js" type="text/javascript"></script>
</head>

<body>

    <!-- Left side content -->
    <div id="left_content">
        <div id="leftSide" style="padding-top:30px;">

            <!-- Account panel -->

            <div class="sideProfile">
                <a href="#" title="" class="profileFace"></a>
                <span>Xin chào: <strong>admin!</strong></span>
                
                <div class="clear"></div>
            </div>
            <div class="sidebarSep"></div>
            <!-- Left navigation -->

            <ul id="menu" class="nav">

                <li class="home">

                    <a href="admin/home.html" class="active" id="current">
                        <span>Bảng điều khiển</span>
                        <strong></strong>
                    </a>


                </li>
               
                <li class="product">

                   

                    <ul class="sub">
                        <li>
                            <a href="@Url.Action("Index","SanPhamAdmin")">
                                Sản phẩm
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","LoaiSanPham")">
                                Loại sản phẩm
                            </a>
                        </li>
                        
                    </ul>

                </li>
               
                
           

            </ul>

        </div>
        <div class="clear"></div>
 </div>

    <!--Right-->
    <div id="rightSide">
        <div class="topNav">
            <div class="wrapper">
                <div class="welcome">
                    
                </div>

                <div class="userNav">
                    <ul>
                        <li>
                            <a href="" target="_blank">
                                <img style="margin-top:7px;" src="~/Asset/images/icons/light/home.png" />
                                <span>Trang chủ</span>
                            </a>
                        </li>

                        <!-- Logout -->
                        <li>
                            <a href="admin/home/logout.html">
                                <img src="~/Asset/images/icons/topnav/logout.png" alt="" />
                                <span>Đăng xuất</span>
                            </a>
                        </li>

                    </ul>
                </div>

                <div class="clear"></div>
            </div>
        </div>
        @RenderBody()

      </div>
    <div class="clear"></div>


        <!-- Footer -->
        <div id="footer">
            <div class="wrapper">

                <div>Bản quyền © 2012-2016 Hocphp.info</div>
            </div>
        </div>

        <div class="clear"></div>
</body>
</html>